### PR TITLE
support TS-X16

### PR DESCRIPTION
**Pull request by qianxuu**

### CODE REVIEW

**Comment by OneCDOnly** [comment]
Hi @qianxu2001. :)

Thank you for your commit. What is the model of your NAS please?

**Review by OneCDOnly — CHANGES_REQUESTED** [review]
Can you please order the system models alphabetically? 

So, this line looks like `TS-X16|TS-X28A|TS-XA28A|TS-X33|TS-X35EU)`

**Comment by OneCDOnly** [comment]
Change looks great! 👍🏽 

What is your actual NAS model please?

**Review by OneCDOnly — APPROVED** [review]

**Comment by qianxuu** [comment]
> Change looks great! 👍🏽
> 
> What is your actual NAS model please?

My NAS model is the TS-216, part of the TS-X16 series, which is the model sold for mainland China and has most of the same hardware specifications as the TS-233.

Similarly, there is a 4 Bays version of the TS-X16 series, model TS-416, similar to the TS-433.

These models can be found on QNAP's official Chinese website.

https://www.qnap.com.cn/zh-cn/product/series/home#:~:text=%E6%AF%94%E8%BE%83-,TS%2Dx16%20%E7%B3%BB%E5%88%97,-%E9%AB%98%E6%80%A7%E4%BB%B7 (Simplified Chinese)
https://www.qnap.com.cn/zh-cn/product/ts-216/specs/hardware (Simplified Chinese)

**Comment by OneCDOnly** [comment]
Cheers mate. Let's get this thing merged.

**Pull request merged**
